In [16]:
import pandas as pd 
import numpy as np

In [17]:
sm_df = pd.read_csv("./training_set.csv")

In [18]:
sm_df.shape

(100000, 4)

In [19]:
sm_df.head()

id    income      age  \
0   249893612   38083.0  44.8677   
1  2264281529   29429.0  30.2327   
2   555636171  111127.0  29.5693   
3  3976714904   62514.0  37.8036   
4  1773172946   46892.0  34.6590   

                                        friends_list  
0  4202980087,2258284167,4614845762,233604503,650...  
1  26600353,47515927,20896265,23449295,501162087,...  
2  5540122414,4285863106,3061861070,2977843626,14...  
3  791994715,1991840134,3317519232,35655282,27074...  
4  6089602574,6038882552,5681654631,1591004024,42...

In [20]:
# data = sm_df.values
# print(data)

In [21]:
sm_temp_df = sm_df.loc[:,['id','income']]

sm_temp_df.head()

# print(sm_df['id','income'])

id    income
0   249893612   38083.0
1  2264281529   29429.0
2   555636171  111127.0
3  3976714904   62514.0
4  1773172946   46892.0

In [22]:
# income_dict = sm_temp_df.set_index('id').T.to_dict('income')
income_dict = sm_temp_df.set_index("id").to_dict(orient='dict')["income"]

In [23]:
# print(income_dict)

In [24]:
income_dict[3299210613]

50877.0

In [25]:
data = sm_df.values
ids = list(data[:,0])
fri_lists = data[:,3]
avg_income = []

In [28]:
# range(len(fri_lists))
for i, fri_list in zip(range(0,500), fri_lists):
    fri_list = fri_list.split(',')
    income = 0
    count = 0
    # print(fri_list)
    
    for fri_id in fri_list:
        if int(fri_id) in ids:
            income += income_dict[int(fri_id)]
            count += 1
        if count != 0:
            income /= count
    
    # print(income)
    data[i,3] = income
    print(data[i,:])

#data = data [:, [0,1,2,3]]

[249893612 38083.0 44.8677 0]
[2264281529 29429.0 30.2327 0]
[555636171 111127.0 29.5693 0]
[3976714904 62514.0 37.8036 50877.0]
[1773172946 46892.0 34.659 50877.0]
[259246272 20696.0 40.9405 1.6154748524838632e-53]
[2561722778 68617.0 54.7372 4.9351728711721135e-204]
[962668762 17418.0 22.6521 6.3863379782332004e-71]
[2156249765 28759.0 23.2581 5.099412603511496e-121]
[1519471400 75691.0 38.0567 1.419755310601957e-161]
[3163384944 59120.0 35.753 0.0]
[14017536 48262.0 28.6322 3.1138286606307704e-91]
[196603885 18005.0 23.1515 6.622381167660585e-178]
[1059138299 89158.0 38.2605 9.200453466540158e-43]
[2084881349 13448.0 20.8736 4.7286308846046637e-182]
[707438228 107749.0 47.3753 9.001603343284781e-160]
[499405392 38687.0 30.9768 5.654040946492365e-306]
[5584943 140463.0 26.0794 0.0]
[257269678 88160.0 29.8708 0.0]
[400597620 117223.0 33.7958 0.0]
[190148246 36308.0 30.656 0.0]
[305189030 86770.0 37.4435 0.0]
[405734396 52952.0 25.619 0.0]
[19513607 25462.0 26.5537 0.0]
[1964138421 319

[2023557643 54460.0 35.9498 0.0]
[1403480953 31512.0 33.876000000000005 0.0]
[175946417 17850.0 26.5988 0.0]
[3011608166 57219.0 29.5699 0.0]
[313820559 105873.0 25.986 0.0]
[177913159 56201.0 35.9829 0.0]
[314880476 36826.0 25.6431 0.0]
[742902961 24850.0 24.4644 0.0]
[3233349818 42300.0 35.074 0.0]
[276436260 18777.0 22.9775 4.344155399102732e-56]
[266649105 62439.0 38.8503 8.13334550428781e-289]
[275558198 116466.0 26.3214 0.0]
[1059262999 54813.0 33.7464 4.3716923822294514e-210]
[1535752753 20049.0 26.4568 0.0]
[27138521 165930.0 26.1193 0.0]
[301430617 34521.0 29.0312 0.0]
[145040021 75688.0 41.1303 0.0]
[189134406 31123.0 25.7227 6.896206970364537e-218]
[3537957299 22495.0 25.6926 3.3261085963423234e-28]
[322290869 20850.0 33.176500000000004 0.0]
[257948227 64350.0 36.4495 0.0]
[361194556 53367.0 39.46 1.4047997216323e-159]
[6709041 45693.0 33.5138 0.0]
[24337756 59161.0 32.285 0.0]
[48157650 49206.0 28.2675 0.0]
[1240254 73830.0 42.229 0.0]
[744922634 44670.0 29.91 0.0]
[2804689

[614226815 31829.0 25.6512 0.0]
[2233021653 73274.0 48.2823 0.0]
[802169610 13353.0 25.3845 0.0]
[1635575781 27123.0 25.461 0.0]
[301349116 57617.0 41.1697 0.0]
[347872109 149136.0 25.8191 0.0]
[205709292 39138.0 25.7159 0.0]
[1383848557 40205.0 28.3671 1.0191413312885176e-202]
[14371100 35997.0 28.9107 0.0]
[218414892 45026.0 31.3046 0.0]
[1644256878 54043.0 23.7489 0.0]
[412075299 99367.0 55.5838 0.0]
[1226443990 17589.0 19.8018 0.0]
[622098006 110039.0 48.8903 0.0]
[1567716446 55188.0 38.524 0.0]
[6707112 36478.0 27.8383 1.2879619410792833e-20]
[1738711934 53415.0 32.685900000000004 0.0]
[317181852 14282.0 21.9754 0.0]
[3940000697 102268.0 49.8893 0.0]
[235114456 68096.0 36.9907 0.0]
[891302505 51589.0 30.9251 0.0]
[2102865019 25006.0 23.6828 0.0]
[2533162218 173307.0 19.4835 0.0]
[2025124358 95035.0 36.0545 0.0]
[278997290 26795.0 25.6026 8.0374759558934e-276]
[3217601722 15332.0 20.7159 0.0]
[15938477 109793.0 48.9676 0.0]
[1515394913 36378.0 26.9042 1.0486858397728684e-42]
[18014

In [36]:
for i, fri_list in zip(range(len(fri_lists)), fri_lists):
    fri_list = fri_list.split(',')
    if '#' in fri_list[0]:
        continue
    income = 0
    count = 0
    for fri_id in fri_list:
        if int(fri_id) in ids:
            income += income_dict[ids_index]
            count += 1
    if count != 0:
        income /= count

    data[i,4] = income
data = data [:, [0,1,2,4]]

IndexError: index 4 is out of bounds for axis 1 with size 4